name: Elasticsearch GitHub Action
on: [push]
jobs:
  run-action:
    name: Start Elasticsearch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elasticsearch: ["8.0.1", "8.2.0", "8.6.2", "8.7.0"]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - name: Start Elasticsearch
        uses: ./
        with:
          stack-version: ${{ matrix.elasticsearch }}
      - name: Elasticsearch is reachable
        run: |
          curl --verbose --show-error http://localhost:9200/_cat/plugins